# Generated by Django 3.2 on 2021-05-22 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YVideoData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('publishing_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail_url', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'yvideo_data',
                'managed': True,
            },
        ),
    ]
